#:schema node_modules/wrangler/config-schema.json
name = "aka-sublink"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "466c3ebf25734e3989cba994d566275f" }
]

[assets]
directory = "./public"
